# Generated by Django 5.2.4 on 2025-09-13 23:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-request_date'], 'verbose_name': 'تسجيل', 'verbose_name_plural': 'التسجيلات'},
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='students.teacher', verbose_name='المعلم المسؤول'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='معتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='request_status',
            field=models.CharField(choices=[('requested', 'مطلوب'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='requested', max_length=10, verbose_name='حالة الطلب'),
        ),
        migrations.AddField(
            model_name='student',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='حالة الاعتماد'),
        ),
        migrations.AddField(
            model_name='student',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=50, verbose_name='المستوى'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('approve', 'اعتماد'), ('reject', 'رفض')], max_length=10, verbose_name='الإجراء')),
                ('model_name', models.CharField(max_length=50, verbose_name='اسم النموذج')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف العنصر')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='الطابع الزمني')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-timestamp'],
            },
        ),
    ]
